
print('+---------------------------------------------------------------------+')
print('|                                                       October 2023  |')
print('|                                                      Madrid, Spain  |')
print('|  Dear Self,                                                         |')
print('|                                                                     |')
print('|      Build the learn to code platform that you always dreamed of.   |')
print('|      Give more than you take.                                       |')
print('|      Care > capital.                                                |')
print('|      And always get back up.                                        |')
print('|                                                                     |')
print('|                                              Alba Muñoz             |')
print('|                                                                     |')
print('+---------------------------------------------------------------------+')